language: java

jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home

before_install:
  - chmod +x mvnw

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - dante0806@naver.com 