#SPRING MVC SETTINGS
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  h2:
    console:
      enabled: true 
      path: /h2-console
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  #datasource: 
    #data: classpath:data-h2.sql
  profiles:
    active: local #기본환경선택
    
#jsp.. immediately
server:
  servlet:
    jsp:
      init-parameters:  
        development:  true 
logging:
  level:
    root: info 
    
#local환경


      

            
