#SPRING MVC SETTINGS
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  h2:
    console:
      enabled: true 
      path: /h2-console
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      #ddl-auto: update
      ddl-auto: create-drop # 어플리케이션 실행시 마다 테이블을 drop 후 create 함 
    properties:
      hibernate:
        format_sql: true
  datasource:
    platform: h2 
    data: classpath:data-h2.sql
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy  #log4j 드라이버
    url: jdbc:log4jdbc:h2:mem:testdb # H2 DB에 log4j 드라이버 인젝션  //JDBCURL : jdbc:h2:mem:testdb
    username: sa  #H2 DB에 log4j 드라이버를 인젝션하면 db 접속계정이 날아감!!   //sa로 재설정하여 사용
    password: 
  profiles: 
    active: local #기본환경선택
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
      ## 프로젝트내의 폴더에 업로드 파일을 설정하고 싶으면 1:처럼 
      ## 본인 PC의 특정 dir에 업로드 하고 싶으면 2:처럼 설정. 
      #1: location: ./uploads 
      #2: location: /Users/pang/Documents/UPLOAD_FILES
      location: C:/develop/images/
        
    
#jsp.. immediately
server:
  servlet:
    jsp:
      init-parameters:  
        development:  true
logging:
  level:
    root: info 
    
#local환경


      

            
