#SPRING MVC SETTINGS
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  h2:
    console:
      enabled: true 
  #datasource:
   # driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://localhost:8080
    #username: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        #dialect: org.hibernate.dialect.MySQLDialect
        #default_schema:
  profiles:
    active: local #기본환경선택
    
#local환경
  datasource:
    data: classpath:data-h2.sql
      
      
#jsp.. immediately
server:
  servlet:
    jsp:
      init-parameters:  
        development:  true 
logging:
  level:
    root: info
            
